#pragma once

#include <coco/platform/stm32g0.h> // generated by CMake


/// @brief Get device id
///
inline uint32_t getDeviceId() {
    return (DBG->IDCODE & DBG_IDCODE_DEV_ID_Msk) >> DBG_IDCODE_DEV_ID_Pos;
}

/// @brief Get variant id
///
inline uint32_t getVariantId() {
    return (DBG->IDCODE & DBG_IDCODE_REV_ID_Msk) >> DBG_IDCODE_REV_ID_Pos;
}


// convenience constants

// flash wait states
constexpr uint32_t FLASH_ACR_LATENCY_0WS = 0;
constexpr uint32_t FLASH_ACR_LATENCY_1WS = FLASH_ACR_LATENCY_0;
constexpr uint32_t FLASH_ACR_LATENCY_2WS = FLASH_ACR_LATENCY_1;

// HSI48 clock division factor
constexpr uint32_t RCC_CR_HSIDIV_DIV1 = 0; // reset value
constexpr uint32_t RCC_CR_HSIDIV_DIV2 = RCC_CR_HSIDIV_0;
constexpr uint32_t RCC_CR_HSIDIV_DIV4 = RCC_CR_HSIDIV_1;
constexpr uint32_t RCC_CR_HSIDIV_DIV8 = RCC_CR_HSIDIV_1 | RCC_CR_HSIDIV_0;
constexpr uint32_t RCC_CR_HSIDIV_DIV16 = RCC_CR_HSIDIV_2;
constexpr uint32_t RCC_CR_HSIDIV_DIV32 = RCC_CR_HSIDIV_2 | RCC_CR_HSIDIV_0;
constexpr uint32_t RCC_CR_HSIDIV_DIV64 = RCC_CR_HSIDIV_2 | RCC_CR_HSIDIV_1;
constexpr uint32_t RCC_CR_HSIDIV_DIV128 = RCC_CR_HSIDIV_2 | RCC_CR_HSIDIV_1 | RCC_CR_HSIDIV_0;

// AHB prescaler
constexpr uint32_t RCC_CFGR_HPRE_DIV1 = 0;
constexpr uint32_t RCC_CFGR_HPRE_DIV2 = RCC_CFGR_HPRE_3;
constexpr uint32_t RCC_CFGR_HPRE_DIV4 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_0;
constexpr uint32_t RCC_CFGR_HPRE_DIV8 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_1;
constexpr uint32_t RCC_CFGR_HPRE_DIV16 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_1 | RCC_CFGR_PPRE_0;
constexpr uint32_t RCC_CFGR_HPRE_DIV64 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2;
constexpr uint32_t RCC_CFGR_HPRE_DIV128 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_0;
constexpr uint32_t RCC_CFGR_HPRE_DIV256 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1;
constexpr uint32_t RCC_CFGR_HPRE_DIV512 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1 | RCC_CFGR_PPRE_0;

// APB prescaler
constexpr uint32_t RCC_CFGR_PPRE_DIV1 = 0;
constexpr uint32_t RCC_CFGR_PPRE_DIV2 = RCC_CFGR_PPRE_2;
constexpr uint32_t RCC_CFGR_PPRE_DIV4 = RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_0;
constexpr uint32_t RCC_CFGR_PPRE_DIV8 = RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1;
constexpr uint32_t RCC_CFGR_PPRE_DIV16 = RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1 | RCC_CFGR_PPRE_0;

// system clock switch
constexpr uint32_t RCC_CFGR_SW_HSISYS = 0;
constexpr uint32_t RCC_CFGR_SW_HSE = RCC_CFGR_SW_0;
constexpr uint32_t RCC_CFGR_SW_PLLRCLK = RCC_CFGR_SW_1;
constexpr uint32_t RCC_CFGR_SW_LSI = RCC_CFGR_SW_1 | RCC_CFGR_SW_0;
constexpr uint32_t RCC_CFGR_SW_LSE = RCC_CFGR_SW_2;
