#pragma once

#include <coco/platform/stm32c0.h> // generated by CMake


// HSI48 prescaler
constexpr int RCC_CR_HSIDIV_DIV1 = 0;
constexpr int RCC_CR_HSIDIV_DIV2 = RCC_CR_HSIDIV_0;
constexpr int RCC_CR_HSIDIV_DIV4 = RCC_CR_HSIDIV_1; // reset value
constexpr int RCC_CR_HSIDIV_DIV8 = RCC_CR_HSIDIV_1 | RCC_CR_HSIDIV_0;
constexpr int RCC_CR_HSIDIV_DIV16 = RCC_CR_HSIDIV_2;
constexpr int RCC_CR_HSIDIV_DIV32 = RCC_CR_HSIDIV_2 | RCC_CR_HSIDIV_0;
constexpr int RCC_CR_HSIDIV_DIV64 = RCC_CR_HSIDIV_2 | RCC_CR_HSIDIV_1;
constexpr int RCC_CR_HSIDIV_DIV128 = RCC_CR_HSIDIV_2 | RCC_CR_HSIDIV_1 | RCC_CR_HSIDIV_0;

// AHB prescaler
constexpr int RCC_CFGR_HPRE_DIV1 = 0;
constexpr int RCC_CFGR_HPRE_DIV2 = RCC_CFGR_HPRE_3;
constexpr int RCC_CFGR_HPRE_DIV4 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_0;
constexpr int RCC_CFGR_HPRE_DIV8 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_1;
constexpr int RCC_CFGR_HPRE_DIV16 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_1 | RCC_CFGR_PPRE_0;
constexpr int RCC_CFGR_HPRE_DIV64 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2;
constexpr int RCC_CFGR_HPRE_DIV128 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_0;
constexpr int RCC_CFGR_HPRE_DIV256 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1;
constexpr int RCC_CFGR_HPRE_DIV512 = RCC_CFGR_HPRE_3 | RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1 | RCC_CFGR_PPRE_0;

// APB prescaler
constexpr int RCC_CFGR_PPRE_DIV1 = 0;
constexpr int RCC_CFGR_PPRE_DIV2 = RCC_CFGR_PPRE_2;
constexpr int RCC_CFGR_PPRE_DIV4 = RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_0;
constexpr int RCC_CFGR_PPRE_DIV8 = RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1;
constexpr int RCC_CFGR_PPRE_DIV16 = RCC_CFGR_PPRE_2 | RCC_CFGR_PPRE_1 | RCC_CFGR_PPRE_0;


/**
 * Get device id
 */
inline uint32_t getDeviceId() {
    return (DBG->IDCODE & DBG_IDCODE_DEV_ID_Msk) >> DBG_IDCODE_DEV_ID_Pos;
}

/**
 * Get variant id
 */
inline uint32_t getVariantId() {
    return (DBG->IDCODE & DBG_IDCODE_REV_ID_Msk) >> DBG_IDCODE_REV_ID_Pos;
}
