#pragma once

#include <coco/platform/stm32u3.h> // generated by CMake

// don't use runtime detected flash size for now (instead define actual flash size in config.h of the project)
#undef FLASH_SIZE


/// @brief Get device id
///
inline uint32_t getDeviceId() {
    // read DBGMCU_IDCODE register
    return *(const uint32_t *)(0xE0042000) & 0xfff;
}

/// @brief Get variant id
///
inline uint32_t getVariantId() {
    // read DBGMCU_IDCODE register
    return (*(const uint32_t *)(0xE0042000) >> 16) & 0xffff;
}

// convenience constants
constexpr uint32_t FLASH_ACR_LATENCY_0WS = 0;
constexpr uint32_t FLASH_ACR_LATENCY_1WS = FLASH_ACR_LATENCY_0;
constexpr uint32_t FLASH_ACR_LATENCY_2WS = FLASH_ACR_LATENCY_1;
constexpr uint32_t FLASH_ACR_LATENCY_3WS = FLASH_ACR_LATENCY_1 | FLASH_ACR_LATENCY_0;
constexpr uint32_t FLASH_ACR_LATENCY_4WS = FLASH_ACR_LATENCY_2;

constexpr uint32_t RCC_CFGR2_HPRE1_DIV1 = 0;

constexpr uint32_t RCC_CFGR2_PPRE1_DIV4 = RCC_CFGR2_PPRE1_2 | RCC_CFGR2_PPRE1_0;

constexpr uint32_t RCC_CFGR2_PPRE2_DIV4 = RCC_CFGR2_PPRE2_2 | RCC_CFGR2_PPRE2_0;

constexpr uint32_t RCC_CFGR3_PPRE3_DIV4 = RCC_CFGR3_PPRE3_2 | RCC_CFGR3_PPRE3_0;

constexpr uint32_t RCC_ICSCR1_MSIS_96MHZ = 0;
constexpr uint32_t RCC_ICSCR1_MSIS_48MHZ = RCC_ICSCR1_MSISDIV_0;
constexpr uint32_t RCC_ICSCR1_MSIS_24MHZ = RCC_ICSCR1_MSISSEL;
constexpr uint32_t RCC_ICSCR1_MSIS_12MHZ = RCC_ICSCR1_MSISSEL | RCC_ICSCR1_MSISDIV_0;
constexpr uint32_t RCC_ICSCR1_MSIS_6MHZ = RCC_ICSCR1_MSISSEL | RCC_ICSCR1_MSISDIV_1;
constexpr uint32_t RCC_ICSCR1_MSIS_3MHZ = RCC_ICSCR1_MSISSEL | RCC_ICSCR1_MSISDIV_1 | RCC_ICSCR1_MSISDIV_0;

constexpr uint32_t RCC_ICSCR1_MSIK_96MHZ = 0;
constexpr uint32_t RCC_ICSCR1_MSIK_48MHZ = RCC_ICSCR1_MSIKDIV_0;
constexpr uint32_t RCC_ICSCR1_MSIK_24MHZ = RCC_ICSCR1_MSIKSEL;
constexpr uint32_t RCC_ICSCR1_MSIK_12MHZ = RCC_ICSCR1_MSIKSEL | RCC_ICSCR1_MSIKDIV_0;
constexpr uint32_t RCC_ICSCR1_MSIK_6MHZ = RCC_ICSCR1_MSIKSEL | RCC_ICSCR1_MSIKDIV_1;
constexpr uint32_t RCC_ICSCR1_MSIK_3MHZ = RCC_ICSCR1_MSIKSEL | RCC_ICSCR1_MSIKDIV_1 | RCC_ICSCR1_MSIKDIV_0;
