#pragma once

#include <coco/platform/stm32h5.h> // select device header (generated by CMake)


#define STM32
#define STM32H5


// don't use runtime detected flash size for now (instead define actual flash size in config.h of the project)
#undef FLASH_SIZE


// convenience constants
constexpr uint32_t RCC_CFGR2_HPRE1_DIV1 = 0;

constexpr uint32_t RCC_CFGR2_PPRE1_DIV4 = RCC_CFGR2_PPRE1_2 | RCC_CFGR2_PPRE1_0;
constexpr uint32_t RCC_CFGR2_PPRE1_DIV8 = RCC_CFGR2_PPRE1_2 | RCC_CFGR2_PPRE1_1;

constexpr uint32_t RCC_CFGR2_PPRE2_DIV4 = RCC_CFGR2_PPRE2_2 | RCC_CFGR2_PPRE2_0;
constexpr uint32_t RCC_CFGR2_PPRE2_DIV8 = RCC_CFGR2_PPRE2_2 | RCC_CFGR2_PPRE2_1;

constexpr uint32_t RCC_CFGR2_PPRE3_DIV4 = RCC_CFGR2_PPRE3_2 | RCC_CFGR2_PPRE3_0;
constexpr uint32_t RCC_CFGR2_PPRE3_DIV8 = RCC_CFGR2_PPRE3_2 | RCC_CFGR2_PPRE3_1;
