#pragma once

#include <coco/platform/stm32h5.h> // generated by CMake

// don't use runtime detected flash size for now (instead define actual flash size in config.h of the project)
#undef FLASH_SIZE


/// @brief Get device id
///
inline uint32_t getDeviceId() {
    // read DBGMCU_IDCODE register
    return *(const uint32_t *)(0xE0042000) & 0xfff;
}

/// @brief Get variant id
///
inline uint32_t getVariantId() {
    // read DBGMCU_IDCODE register
    return (*(const uint32_t *)(0xE0042000) >> 16) & 0xffff;
}

// convenience constants
constexpr uint32_t RCC_CFGR2_HPRE1_DIV1 = 0;

constexpr uint32_t RCC_CFGR2_PPRE1_DIV4 = RCC_CFGR2_PPRE1_2 | RCC_CFGR2_PPRE1_0;
constexpr uint32_t RCC_CFGR2_PPRE1_DIV8 = RCC_CFGR2_PPRE1_2 | RCC_CFGR2_PPRE1_1;

constexpr uint32_t RCC_CFGR2_PPRE2_DIV4 = RCC_CFGR2_PPRE2_2 | RCC_CFGR2_PPRE2_0;
constexpr uint32_t RCC_CFGR2_PPRE2_DIV8 = RCC_CFGR2_PPRE2_2 | RCC_CFGR2_PPRE2_1;

constexpr uint32_t RCC_CFGR2_PPRE3_DIV4 = RCC_CFGR2_PPRE3_2 | RCC_CFGR2_PPRE3_0;
constexpr uint32_t RCC_CFGR2_PPRE3_DIV8 = RCC_CFGR2_PPRE3_2 | RCC_CFGR2_PPRE3_1;
