# Run this script after installing the conan dependencies for all profiles
# Command line: python3 presets.py
# VSCode: Right click on presets.py and select "Run Python File in Terminal"

import os
import json


# collect CMakePresets.json from the build directories which are generated by conan install
configurePresets = []
buildPresets = []
testPresets = []
for dir in os.listdir("build"):
    print(dir)

    file = open(f"build/{dir}/CMakePresets.json")
    presets = json.load(file)
    file.close()

    configurePreset = presets["configurePresets"]
    buildPreset = presets["buildPresets"]
    testPreset = presets["testPresets"]

    for p in configurePreset:
        p["name"] = dir
        p.pop("displayName", None)
        p.pop("binaryDir", None)
    for p in buildPreset:
        p["name"] = dir
        p["configurePreset"] = dir

    configurePresets.extend(configurePreset)
    buildPresets.extend(buildPreset)
    testPresets.extend(testPreset)


# assemble combined presets
presets = {
    "version": 3,
    "configurePresets": configurePresets,
    "buildPresets": buildPresets,
    "testPresets": testPresets}


# write CMakeUserPresets.json
with open("CMakeUserPresets.json", 'w') as file:
    json.dump(presets, file, ensure_ascii=False, indent=4)
