#pragma once

#include "adcG4H5.hpp"


namespace coco {
namespace adc {

/// @brief ADC trigger (CFGR register)
/// Reference manual section 21.4.18
enum class Trigger : uint32_t {
    // ADC triggered by software (set ADSTART bit or call start())
    SOFTWARE = 0,

    // ADC1/ADC2 triggered by...
    ADC12_TIM1_OC1 = ADC_CFGR_EXTEN_0 | (0 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM1_OC2 = ADC_CFGR_EXTEN_0 | (1 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM1_OC3 = ADC_CFGR_EXTEN_0 | (2 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM1_TRGO = ADC_CFGR_EXTEN_0 | (9 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM1_TRGO2 = ADC_CFGR_EXTEN_0 | (10 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM2_OC2 = ADC_CFGR_EXTEN_0 | (3 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM2_TRGO = ADC_CFGR_EXTEN_0 | (11 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM3_OC4 = ADC_CFGR_EXTEN_0 | (15 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM3_TRGO = ADC_CFGR_EXTEN_0 | (4 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM4_OC4 = ADC_CFGR_EXTEN_0 | (5 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM4_TRGO = ADC_CFGR_EXTEN_0 | (12 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM6_TRGO = ADC_CFGR_EXTEN_0 | (13 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM7_TRGO = ADC_CFGR_EXTEN_0 | (30 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM8_TRGO = ADC_CFGR_EXTEN_0 | (7 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM8_TRGO2 = ADC_CFGR_EXTEN_0 | (8 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM15_TRGO = ADC_CFGR_EXTEN_0 | (14 << ADC_CFGR_EXTSEL_Pos),
#ifdef TIM20
    ADC12_TIM20_OC1 = ADC_CFGR_EXTEN_0 | (18 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM20_OC2 = ADC_CFGR_EXTEN_0 | (19 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM20_OC3 = ADC_CFGR_EXTEN_0 | (20 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM20_TRGO = ADC_CFGR_EXTEN_0 | (16 << ADC_CFGR_EXTSEL_Pos),
    ADC12_TIM20_TRGO2 = ADC_CFGR_EXTEN_0 | (17 << ADC_CFGR_EXTSEL_Pos),
#endif
#ifdef HRTIM1
    ADC12_HRTIM_ADC_TRG1 = ADC_CFGR_EXTEN_0 | (21 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG3 = ADC_CFGR_EXTEN_0 | (22 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG5 = ADC_CFGR_EXTEN_0 | (23 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG6 = ADC_CFGR_EXTEN_0 | (24 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG7 = ADC_CFGR_EXTEN_0 | (25 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG8 = ADC_CFGR_EXTEN_0 | (26 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG9 = ADC_CFGR_EXTEN_0 | (27 << ADC_CFGR_EXTSEL_Pos),
    ADC12_HRTIM_ADC_TRG10 = ADC_CFGR_EXTEN_0 | (28 << ADC_CFGR_EXTSEL_Pos),
#endif
    ADC12_LPTIM_OUT = ADC_CFGR_EXTEN_0 | (29 << ADC_CFGR_EXTSEL_Pos),
    ADC12_EXTI11 = ADC_CFGR_EXTEN_0 | (6 << ADC_CFGR_EXTSEL_Pos),

#ifdef ADC3
    // ADC3/ADC4/ADC5 triggered by...
    ADC345_TIM1_OC3 = ADC_CFGR_EXTEN_0 | (2 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM1_TRGO = ADC_CFGR_EXTEN_0 | (9 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM1_TRGO2 = ADC_CFGR_EXTEN_0 | (10 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM2_OC1 = ADC_CFGR_EXTEN_0 | (15 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM2_OC3 = ADC_CFGR_EXTEN_0 | (1 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM2_TRGO = ADC_CFGR_EXTEN_0 | (11 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM3_OC1 = ADC_CFGR_EXTEN_0 | (0 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM3_TRGO = ADC_CFGR_EXTEN_0 | (4 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM4_TRGO = ADC_CFGR_EXTEN_0 | (12 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM6_TRGO = ADC_CFGR_EXTEN_0 | (13 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM7_TRGO = ADC_CFGR_EXTEN_0 | (30 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM8_OC1 = ADC_CFGR_EXTEN_0 | (3 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM8_TRGO = ADC_CFGR_EXTEN_0 | (7 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM8_TRGO2 = ADC_CFGR_EXTEN_0 | (8 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM15_TRGO = ADC_CFGR_EXTEN_0 | (14 << ADC_CFGR_EXTSEL_Pos),
#ifdef TIM20
    ADC345_TIM20_OC1 = ADC_CFGR_EXTEN_0 | (18 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM20_TRGO = ADC_CFGR_EXTEN_0 | (16 << ADC_CFGR_EXTSEL_Pos),
    ADC345_TIM20_TRGO2 = ADC_CFGR_EXTEN_0 | (17 << ADC_CFGR_EXTSEL_Pos),
#endif
#ifdef HRTIM1
    ADC345_HRTIM_ADC_TRG1 = ADC_CFGR_EXTEN_0 | (21 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG2 = ADC_CFGR_EXTEN_0 | (19 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG3 = ADC_CFGR_EXTEN_0 | (22 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG4 = ADC_CFGR_EXTEN_0 | (20 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG5 = ADC_CFGR_EXTEN_0 | (23 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG6 = ADC_CFGR_EXTEN_0 | (24 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG7 = ADC_CFGR_EXTEN_0 | (25 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG8 = ADC_CFGR_EXTEN_0 | (26 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG9 = ADC_CFGR_EXTEN_0 | (27 << ADC_CFGR_EXTSEL_Pos),
    ADC345_HRTIM_ADC_TRG10 = ADC_CFGR_EXTEN_0 | (28 << ADC_CFGR_EXTSEL_Pos),
#endif
    ADC345_LPTIM_OUT = ADC_CFGR_EXTEN_0 | (29 << ADC_CFGR_EXTSEL_Pos),
    ADC345_EXTI2 = ADC_CFGR_EXTEN_0 | (5 << ADC_CFGR_EXTSEL_Pos),
#endif
};


template <dma::Feature F2>
void Info::map(const dma::Info<F2> &dmaInfo) const {
    dmaInfo.setRequest(drq);
}

template <dma::Feature F2>
void DualInfo::map(const dma::Info<F2> &dmaInfo, int channelIndex) const {
    dmaInfo.setRequest(drq + channelIndex);
}


// single channel ADC infos
static const Info ADC1_INFO{ADC12_COMMON, ADC1, RCC_AHB2ENR_ADC12EN, ADC1_2_IRQn, 5};
static const Info ADC2_INFO{ADC12_COMMON, ADC2, RCC_AHB2ENR_ADC12EN, ADC1_2_IRQn, 36};
#ifdef ADC3
static const Info ADC3_INFO{ADC345_COMMON, ADC3, RCC_AHB2ENR_ADC345EN, ADC3_IRQn, 37};
#endif
#ifdef ADC4
static const Info ADC4_INFO{ADC345_COMMON, ADC4, RCC_AHB2ENR_ADC345EN, ADC4_IRQn, 38};
#endif
#ifdef ADC5
static const Info ADC5_INFO{ADC345_COMMON, ADC5, RCC_AHB2ENR_ADC345EN, ADC5_IRQn, 39};
#endif

// dual channel ADC infos
static const DualInfo ADC12_INFO{ADC12_COMMON, ADC1, ADC2, RCC_AHB2ENR_ADC12EN, ADC1_2_IRQn, 5};
#ifdef ADC4
static const DualInfo ADC34_INFO{ADC345_COMMON, ADC3, ADC4, RCC_AHB2ENR_ADC345EN, ADC3_IRQn, 37};
#endif

} // namespace adc
} // namespace coco
