#pragma once

#include "platform.hpp"
#include <coco/enum.hpp>


namespace coco {

/// @brief COMP helpers
/// Refernece manual: https://www.st.com/resource/en/reference_manual/rm0440-stm32g4-series-advanced-armbased-32bit-mcus-stmicroelectronics.pdf
///   Section 24
namespace comp {

enum class Config : uint32_t {
    // output
    OUT_INVERT = COMP_CSR_POLARITY,

    // plus input
    COMP1_INP_PA1 = 0,
    COMP1_INP_PB1 = COMP_CSR_INPSEL,

    COMP2_INP_PA7 = 0,
    COMP2_INP_PA3 = COMP_CSR_INPSEL,

    COMP3_INP_PA0 = 0,
    COMP3_INP_PC1 = COMP_CSR_INPSEL,

    COMP4_INP_PB0 = 0,
    COMP4_INP_PE7 = COMP_CSR_INPSEL,

    COMP5_INP_PB13 = 0,
    COMP5_INP_PD12 = COMP_CSR_INPSEL,

    COMP6_INP_PB11 = 0,
    COMP6_INP_PD11 = COMP_CSR_INPSEL,

    COMP7_INP_PB14 = 0,
    COMP7_INP_PD14 = COMP_CSR_INPSEL,

    // minus input
    INM_1_4_VREFINT = COMP_CSR_SCALEN | COMP_CSR_BRGEN,
    INM_1_2_VREFINT = COMP_CSR_SCALEN | COMP_CSR_BRGEN | COMP_CSR_INMSEL_0,
    INM_3_4_VREFINT = COMP_CSR_SCALEN | COMP_CSR_BRGEN | COMP_CSR_INMSEL_1,
    INM_VREFINT = COMP_CSR_SCALEN | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP1_INM_DAC3_CH1 = COMP_CSR_INMSEL_2,
    COMP1_INM_DAC1_CH1 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP1_INM_PA4 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP1_INM_PA0 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP2_INM_DAC3_CH2 = COMP_CSR_INMSEL_2,
    COMP2_INM_DAC1_CH2 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP2_INM_PA5 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP2_INM_PA2 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP3_INM_DAC3_CH1 = COMP_CSR_INMSEL_2,
    COMP3_INM_DAC1_CH1 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP3_INM_PF1 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP3_INM_PC0 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP4_INM_DAC3_CH2 = COMP_CSR_INMSEL_2,
    COMP4_INM_DAC1_CH1 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP4_INM_PE8 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP4_INM_PB2 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP5_INM_DAC4_CH1 = COMP_CSR_INMSEL_2,
    COMP5_INM_DAC1_CH2 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP5_INM_PB10 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP5_INM_PD13 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP6_INM_DAC4_CH2 = COMP_CSR_INMSEL_2,
    COMP6_INM_DAC2_CH1 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP6_INM_PD10 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP6_INM_PB15 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    COMP7_INM_DAC4_CH1 = COMP_CSR_INMSEL_2,
    COMP7_INM_DAC2_CH1 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_0,
    COMP7_INM_PD15 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1,
    COMP7_INM_PB12 = COMP_CSR_INMSEL_2 | COMP_CSR_INMSEL_1 | COMP_CSR_INMSEL_0,

    // hysteresis
    HYST_NONE = 0, // default
    HYST_10MV = COMP_CSR_HYST_0,
    HYST_20MV = COMP_CSR_HYST_1,
    HYST_30MV = COMP_CSR_HYST_1 | COMP_CSR_HYST_0,
    HYST_40MV = COMP_CSR_HYST_2,
    HYST_50MV = COMP_CSR_HYST_2 | COMP_CSR_HYST_0,
    HYST_60MV = COMP_CSR_HYST_2 | COMP_CSR_HYST_1,
    HYST_70MV = COMP_CSR_HYST_2 | COMP_CSR_HYST_1 | COMP_CSR_HYST_0,

    // lock configuration register (can only be set, reset by system reset)
    LOCK = COMP_CSR_LOCK
};
COCO_ENUM(Config)

/// @param Configure a comparator.
/// Make sure SYSCFG clock enable bit is set (RCC->APB2ENR = RCC->APB2ENR | RCC_APB2ENR_SYSCFGEN)
inline void enable(COMP_TypeDef *comp, Config config) {
    comp->CSR = COMP_CSR_EN | int(config);
}

/// @param Disable an op-amp
///
inline void disable(COMP_TypeDef *opamp) {
    opamp->CSR = 0;
}

} // namespace comp
} // namespace coco
