#pragma once

#include "dacG0L4G4H5U3U5.hpp"


namespace coco {
namespace dac {

/// @brief DAC trigger
/// Reference manual section 22.4.2
enum class Trigger {
    NONE = 0,

    // DAC triggered by software (via SWTRIGR register)
    SOFTWARE = DAC_CR_TEN1,

    // DAC1 triggered by...
    DAC1_TIM2_TRGO = (4 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_TIM3_TRGO = (8 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_TIM4_TRGO = (5 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_TIM6_TRGO = (7 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_TIM7_TRGO = (2 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_TIM8_TRGO = (1 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_TIM15_TRGO = (3 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#ifdef HRTIM1
    DAC1_HRTIM_DAC_RESET_TRG1 = (9 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_HRTIM_DAC_RESET_TRG2 = (10 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_HRTIM_DAC_RESET_TRG3 = (11 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_HRTIM_DAC_RESET_TRG4 = (12 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_HRTIM_DAC_RESET_TRG5 = (13 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_HRTIM_DAC_RESET_TRG6 = (14 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC1_HRTIM_DAC_TRG1 = (15 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#endif
    DAC1_EXTI9 = (6 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,

    // DAC2 triggered by...
    DAC2_TIM2_TRGO = (4 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_TIM3_TRGO = (8 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_TIM4_TRGO = (5 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_TIM6_TRGO = (7 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_TIM7_TRGO = (2 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_TIM8_TRGO = (1 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_TIM15_TRGO = (3 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#ifdef HRTIM1
    DAC2_HRTIM_DAC_RESET_TRG1 = (9 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_HRTIM_DAC_RESET_TRG2 = (10 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_HRTIM_DAC_RESET_TRG3 = (11 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_HRTIM_DAC_RESET_TRG4 = (12 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_HRTIM_DAC_RESET_TRG5 = (13 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_HRTIM_DAC_RESET_TRG6 = (14 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC2_HRTIM_DAC_TRG2 = (15 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#endif
    DAC2_EXTI9 = (6 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,

    // DAC3 triggered by...
    DAC3_TIM1_TRGO = (1 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_TIM2_TRGO = (4 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_TIM3_TRGO = (8 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_TIM4_TRGO = (5 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_TIM6_TRGO = (7 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_TIM7_TRGO = (2 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_TIM15_TRGO = (3 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#ifdef HRTIM1
    DAC3_HRTIM_DAC_RESET_TRG1 = (9 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_HRTIM_DAC_RESET_TRG2 = (10 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_HRTIM_DAC_RESET_TRG3 = (11 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_HRTIM_DAC_RESET_TRG4 = (12 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_HRTIM_DAC_RESET_TRG5 = (13 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_HRTIM_DAC_RESET_TRG6 = (14 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC3_HRTIM_DAC_TRG3 = (15 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#endif
    DAC3_EXTI9 = (6 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,

    // DAC4 triggered by...
    DAC4_TIM2_TRGO = (4 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_TIM3_TRGO = (8 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_TIM4_TRGO = (5 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_TIM6_TRGO = (7 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_TIM7_TRGO = (2 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_TIM8_TRGO = (1 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_TIM15_TRGO = (3 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#ifdef HRTIM1
    DAC4_HRTIM_DAC_RESET_TRG1 = (9 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_HRTIM_DAC_RESET_TRG2 = (10 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_HRTIM_DAC_RESET_TRG3 = (11 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_HRTIM_DAC_RESET_TRG4 = (12 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_HRTIM_DAC_RESET_TRG5 = (13 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_HRTIM_DAC_RESET_TRG6 = (14 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
    DAC4_HRTIM_DAC_TRG1 = (15 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
#endif
    DAC4_EXTI9 = (6 << DAC_CR_TSEL1_Pos) | DAC_CR_TEN1,
};


template <dma::Feature F2>
void Info::map(const dma::Info<F2> &dmaInfo, int channelIndex) const {
    dmaInfo.setRequest(drq + channelIndex);
}


static const Info DAC1_INFO{DAC1, RCC_AHB2ENR_DAC1EN, TIM6_DAC_IRQn, 6};
#ifdef DAC2
static const Info DAC2_INFO{DAC2, RCC_AHB2ENR_DAC2EN, TIM7_DAC_IRQn, 41};
#endif
static const Info DAC3_INFO{DAC3, RCC_AHB2ENR_DAC3EN, TIM6_DAC_IRQn, 102};
#ifdef DAC4
static const Info DAC4_INFO{DAC4, RCC_AHB2ENR_DAC4EN, TIM7_DAC_IRQn, 104};
#endif

} // namespace dac
} // namespace coco
