#pragma once

#include <coco/platform/stm32g4.h> // select device header (generated by CMake)


#define STM32
#define STM32G4


/// @brief Get device id
///
inline uint32_t getDeviceId() {
    // read DBGMCU_IDCODE register
    return *(const uint32_t *)(0xE0042000) & 0xfff;
}

/// @brief Get variant id
///
inline uint32_t getVariantId() {
    // read DBGMCU_IDCODE register
    return (*(const uint32_t *)(0xE0042000) >> 16) & 0xffff;
}
